/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface DatabaseFirewallRules {
  create_date: Date;
  end_ip_address: string;
  id: Generated<number>;
  modify_date: Date;
  name: unknown;
  start_ip_address: string;
}

export interface Sysdiagrams {
  definition: Buffer | null;
  diagram_id: Generated<number>;
  name: unknown;
  principal_id: number;
  version: number | null;
}

export interface TblAfpuntenKosten {
  AfpuntenFactuurNummer: string;
  AfpuntenGewijzigdDoor: string | null;
  AfpuntenGewijzigdOp: Date | null;
  AfpuntenKostenAantal: number | null;
  AfpuntenKostenBedrag: number | null;
  AfpuntenKostenBegrotingID: string;
  AfpuntenKostenDatum: Date | null;
  AfpuntenKostenGUID: Generated<string>;
  AfpuntenKostenOpmerking: string | null;
  AfpuntenKostenProjectID: string;
}

export interface TblAnalyses {
  AnalysesGUID: Generated<string>;
  AnalysesIntern: boolean | null;
  AnalysesOmschrijving: string | null;
}

export interface TblBasisBegroting {
  BasisBegrotingActief: boolean | null;
  BasisBegrotingGewijzigdDoor: string | null;
  BasisBegrotingGewijzigdOp: Date | null;
  BasisBegrotingGUID: Generated<string>;
  BasisBegrotingInfo: string | null;
  BasisBegrotingIntern: boolean | null;
  BasisBegrotingOmschrijving: string | null;
  BasisBegrotingTarief: number | null;
  BasisBegrotingType: string | null;
}

export interface TblBegroting {
  BegrotingAantal: number | null;
  BegrotingBasisID: string | null;
  BegrotingGefactureerd: number | null;
  BegrotingGewijzigdDoor: string | null;
  BegrotingGewijzigdOp: Date | null;
  BegrotingGUID: Generated<string>;
  BegrotingInfo: string | null;
  BegrotingOmschrijving: string;
  BegrotingProjectID: string | null;
  BegrotingTarief: number | null;
  BegrotingType: string;
}

export interface TblBegrotingPakket {
  BegrotingPakketActief: boolean | null;
  BegrotingPakketGUID: Generated<string>;
  BegrotingPakketOmschrijving: string | null;
}

export interface TblContacten {
  ContactAankoop: Generated<boolean | null>;
  ContactFullName: Generated<string>;
  ContactFunctie: string | null;
  ContactGewijzigdDoor: string | null;
  ContactGewijzigdOp: Date | null;
  ContactGSM: string | null;
  ContactGUID: Generated<string>;
  ContactHistoriek: string | null;
  ContactMail: string | null;
  ContactMedewerker: Generated<boolean | null>;
  ContactMedewerkerActief: Generated<boolean | null>;
  ContactMedewerkerProfiel: number | null;
  ContactNaam: string;
  ContactRelatieID: string | null;
  ContactTelefoon: string | null;
  ContactVoornaam: string;
}

export interface TblFacturen {
  FactuurBedragBruto: number | null;
  FactuurBedragNetto: number | null;
  FactuurDateAsInt: Generated<number | null>;
  FactuurDatum: Date;
  FactuurExport: Generated<boolean | null>;
  FactuurGemaakt: Generated<boolean | null>;
  FactuurGewijzigdDoor: string | null;
  FactuurGewijzigdOp: Date | null;
  FactuurGUID: Generated<string>;
  FactuurMededeling: string | null;
  FactuurNotities: string | null;
  FactuurNummer: string;
  FactuurOK: Generated<boolean | null>;
  FactuurProjectID: string | null;
  FactuurProjectSoortID: string | null;
  FactuurRelatieID: string | null;
  FactuurTitel: number;
  FactuurType: string;
}

export interface TblFactuurDetails {
  FactuurDetailsAantal: number | null;
  FactuurDetailsBegrotingID: string | null;
  FactuurDetailsFactuurID: string | null;
  FactuurDetailsGewijzigdDoor: string | null;
  FactuurDetailsGewijzigdOp: Date | null;
  FactuurDetailsGUID: Generated<string>;
}

export interface TblIntAfwezig {
  IntAfwezigGewijzigdDoor: string | null;
  IntAfwezigGewijzigdOp: Date | null;
  IntAfwezigGUID: Generated<string>;
  IntAfwezigInterneTaakID: string | null;
  IntAfwezigJaar: number | null;
  IntAfwezigLimietUren: number | null;
  IntAfwezigMedewerkerID: string | null;
  IntAfwezigTemp: string | null;
  IntAfwezigVerbruikUren: number | null;
}

export interface TblInterneKosten {
  InterneKostBasisBegrotingID: string;
  InterneKostGewijzigdDoor: string | null;
  InterneKostGewijzigdOp: Date | null;
  InterneKostJaar: number | null;
  InterneKostTarief: number | null;
  InternKostGUID: string;
}

export interface TblInterneTaken {
  InterneTaakActief: boolean | null;
  InterneTaakGewijzigdDoor: string | null;
  InterneTaakGewijzigdOp: Date | null;
  InterneTaakGUID: Generated<string>;
  InterneTaakKlasse: string | null;
  InterneTaakOmschrijving: string | null;
  InterneTaakVerlof: boolean | null;
  InterneTaakVerlofMetLimiet: boolean | null;
  InterneTaakVerlofType: number | null;
  InterneTaakVoorbeelden: string | null;
}

export interface TblLocaties {
  LocatieFull: Generated<string | null>;
  LocatieGewijzigdDoor: string | null;
  LocatieGewijzigdOp: Date | null;
  LocatieGUID: Generated<string>;
  LocatieLand: string | null;
  LocatiePlaats: string | null;
  LocatiePostcode: string | null;
}

export interface TblMetingen {
  MetingAfwijkingMeting: string | null;
  MetingAfwijkingSonde: string | null;
  MetingenParameterID: string | null;
  MetingGUID: Generated<string>;
  MetingMNID: string | null;
  MetingMPID: string | null;
  MetingParameter: string | null;
  MetingProjectID: string | null;
  MetingSnelheidAantal: number | null;
  MetingSnelheidAfwijking: number | null;
  MetingSnelheidMax: number | null;
  MetingSnelheidMin: number | null;
  MetingSonde: string | null;
  MetingStatus: string | null;
  MetingTijdstip: Date | null;
  MetingToestel: string | null;
  MetingWaarde: number | null;
}

export interface TblMonstername {
  MNDatum: Date | null;
  MNProjectID: string | null;
  MonsternameGUID: Generated<string>;
}

export interface TblMonsternamepunten {
  MPActief: Generated<boolean | null>;
  MPBreedte: number | null;
  MPConform: Generated<boolean | null>;
  MPGUID: Generated<string>;
  MPLengte: number | null;
  MPOmschrijving: string | null;
  MPVestigingID: string | null;
}

export interface TblMonsters {
  MonsterAnalyseID: string | null;
  MonsterCodeMedium: string | null;
  MonsterGUID: Generated<string>;
  MonsterMNID: string | null;
  MonsterMPID: string | null;
  MonsterProjectID: string | null;
  MonsterStart: Date | null;
  MonsterStatus: string | null;
  MonsterStop: Date | null;
}

export interface TblParameters {
  ParameterGUID: Generated<string>;
  ParameterOmschrijving: string | null;
  ParameterType: string | null;
}

export interface TblProjecten {
  ProjectAanbrengerID: string | null;
  ProjectCode: Generated<string | null>;
  ProjectContactID: string | null;
  ProjectDatumBevestiging: Date | null;
  ProjectDatumEind: Date | null;
  ProjectDatumOfferte: Date | null;
  ProjectDatumStart: Date | null;
  ProjectDeadline: Date | null;
  ProjectFacturatiePrijs: number | null;
  ProjectFolder: string | null;
  ProjectGewijzigdDoor: string | null;
  ProjectGewijzigdOp: Date | null;
  ProjectGUID: Generated<string>;
  ProjectLeiderID: string | null;
  ProjectMedewerker: string | null;
  ProjectMemoVerval: string | null;
  ProjectOmschrijving: string | null;
  ProjectOpmerking: string | null;
  ProjectReferteKlant: string | null;
  ProjectRegie: boolean | null;
  ProjectRelatieID: string | null;
  ProjectSoortID: string | null;
  ProjectStatusID: string | null;
  ProjectVervalID: string | null;
  ProjectVestigingID: string | null;
}

export interface TblProjectMemo {
  MemoDatum: Date | null;
  MemoGebruiker: string | null;
  MemoGUID: string;
  MemoProjectID: string | null;
  MemoTekst: string | null;
}

export interface TblProjectSoorten {
  ProjectSoortActief: boolean | null;
  ProjectSoortCodeExact: string | null;
  ProjectSoortGewijzigdDoor: string | null;
  ProjectSoortGewijzigdOp: Date | null;
  ProjectSoortGrootBoekrekening: number | null;
  ProjectSoortGUID: Generated<string>;
  ProjectSoortMerk: string | null;
  ProjectSoortOmschrijving: string;
  ProjectSoortSubmap: string | null;
}

export interface TblProjectStatus {
  ProjectStatus: string | null;
  ProjectStatusGewijzigdDoor: string | null;
  ProjectStatusGewijzigdOp: Date | null;
  ProjectStatusGUID: Generated<string>;
}

export interface TblRegistraties {
  DateAsIntEind: Generated<number | null>;
  DateAsIntStart: Generated<number | null>;
  Registratie_EindUur: Date | null;
  Registratie_StartUur: Date | null;
  RegistratieBegrotingID: string | null;
  RegistratieGewijzigdDoor: string | null;
  RegistratieGewijzigdOp: Date | null;
  RegistratieGUID: Generated<string>;
  RegistratieInterneTaakID: string | null;
  RegistratieOmschrijving: string | null;
  RegistratieProjectID: string | null;
  RegistratieTaakVoorProject: Generated<boolean>;
  RegistratieWerknemerID: string;
}

export interface TblRelaties {
  RelatieEmailAdres: string | null;
  RelatieFolder: string | null;
  RelatieGeblokkeerd: Generated<boolean | null>;
  RelatieGewijzigdDoor: string | null;
  RelatieGewijzigdOp: Date | null;
  RelatieGUID: Generated<string>;
  RelatieHistoriek: string | null;
  RelatieKlantnummer: string | null;
  RelatieMemoAlgemeen: string | null;
  RelatieMemoFacturatie: string | null;
  RelatieNaam: string;
  RelatieProblemen: boolean | null;
  RelatieSectorID: string | null;
  RelatieTelefoon: string | null;
  RelatieType: string | null;
  RelatieUrl: string | null;
  RelatieVAT: string | null;
  RelatieVATregime: Generated<number | null>;
}

export interface TblSectoren {
  SectorGewijzigdDoor: string | null;
  SectorGewijzigdOp: Date | null;
  SectorGUID: Generated<string>;
  SectorOmschrijving: string | null;
  SectorVoorbeelden: string | null;
}

export interface TblSensorischeAnalyse {
  SAAangenaamheid: number | null;
  SAGeurkarakter: string | null;
  SAGeuromschrijving: string | null;
  SAGewijzigdDoor: string | null;
  SAGewijzigdOp: Date | null;
  SAGUID: string;
  SAIntensiteit: number | null;
  SAMonsterID: string | null;
  SAPanelID: string | null;
  SATijdStip: Date | null;
}

export interface TblStandaardBegroting {
  StandaardBegrotingAantal: number | null;
  StandaardBegrotingBasisID: string | null;
  StandaardBegrotingGewijzigdDoor: string | null;
  StandaardBegrotingGewijzigdOp: Date | null;
  StandaardBegrotingGUID: Generated<string>;
  StandaardBegrotingInfo: string | null;
  StandaardBegrotingPakketID: string | null;
  StandaardBegrotingProjectSoortID: string | null;
  StandaardBegrotingTarief: number | null;
}

export interface TblUurTarief {
  UurTariefGewijzigdDoor: string | null;
  UurTariefGewijzigdOp: Date | null;
  UurTariefGUID: Generated<string>;
  UurTariefJaar: number | null;
  UurTariefTarief: number | null;
}

export interface TblVerval {
  VervalGUID: Generated<string>;
  VervalNaam: string | null;
  VervalOmschrijving: string | null;
}

export interface TblVestigingen {
  VestigingActief: Generated<boolean | null>;
  VestigingGewijzigdDoor: string | null;
  VestigingGewijzigdOp: Date | null;
  VestigingGUID: Generated<string>;
  VestigingHistoriek: string | null;
  VestigingHuisnummer: string | null;
  VestigingLand: string | null;
  VestigingMZ: Generated<boolean>;
  VestigingNaam: string;
  VestigingPlaats: string | null;
  VestigingPostcode: string | null;
  VestigingRelatieID: string | null;
  VestigingStraat: string | null;
  VestigingTelefoon: string | null;
}

export interface TriggerDebugLog {
  DebugID: Generated<number>;
  EventTime: Generated<Date | null>;
  Message: string | null;
  ProjectCodeAfter: string | null;
  ProjectCodeBefore: string | null;
  ProjectGUID: string | null;
}

export interface ViewAanbrenger {
  RelatieNaam: string;
}

export interface ViewAankoopGegevensOffice {
  ContactAankoop: boolean | null;
  ContactGUID: string;
  ContactMail: string | null;
  ContactRelatieID: string | null;
}

export interface ViewActieveProjecten {
  Project: string | null;
  ProjectCode: string;
  ProjectDatumEind: Date | null;
  ProjectDatumOfferte: Date | null;
  ProjectDatumStart: Date | null;
  ProjectDeadline: Date | null;
  ProjectFacturatiePrijs: number | null;
  ProjectFolder: string | null;
  ProjectGUID: string;
  ProjectLeiderID: string | null;
  ProjectMedewerker: string | null;
  ProjectOmschrijving: string | null;
  ProjectStatus: string | null;
  RelatieNaam: string | null;
}

export interface ViewAfwezig {
  IntAfwezigGUID: string;
  IntAfwezigInterneTaakID: string | null;
  IntAfwezigJaar: number | null;
  IntAfwezigLimietUren: number | null;
  IntAfwezigMedewerkerID: string | null;
  InterneTaakOmschrijving: string | null;
  Verbruik: number | null;
}

export interface ViewAppFoto {
  Project: string | null;
  ProjectCode: string;
  ProjectGUID: string;
  ProjectStatus: string | null;
  RelatieGUID: string | null;
}

export interface ViewAuteurGegevensOffice {
  ContactFullName: string;
  ContactFunctie: string | null;
  ContactGUID: string;
  ContactMail: string | null;
  ContactMedewerker: boolean | null;
  ContactVoornaam: string;
}

export interface ViewBegroting {
  BegrotingAantal: number | null;
  BegrotingGefactureerd: number | null;
  BegrotingGUID: string;
  BegrotingInfo: string | null;
  BegrotingOmschrijving: string;
  BegrotingProjectID: string | null;
  BegrotingTarief: number | null;
  BegrotingType: string;
}

export interface ViewBegrotingDetails {
  BegrotingOmschrijving: string | null;
  ContactFullName: string | null;
  Datum: Date | null;
  Prestatie: number | null;
  ProjectCode: string | null;
  ProjectStatus: string | null;
  RegistratieOmschrijving: string | null;
}

export interface ViewContactenMetRelatie {
  ContactFullName: string;
  ContactGUID: string;
  RelatieNaam: string | null;
}

export interface ViewContactGegevensOffice {
  ContactFullName: string;
  ContactGUID: string;
  ContactMail: string | null;
  ContactRelatieID: string | null;
}

export interface ViewContactMetProject {
  ContactFullName: string;
  RelatieNaam: string;
}

export interface ViewFinancieelPrestaties {
  BegrotingOmschrijving: string | null;
  InterneTaakGUID: string | null;
  InterneTaakKlasse: string | null;
  InterneTaakOmschrijving: string | null;
  Prestatie: number | null;
  ProjectSoortGUID: string | null;
  ProjectSoortOmschrijving: string | null;
  ProjectStatus: string | null;
  Registratie_EindUur: Date | null;
}

export interface ViewFinancieelProductPerMerk {
  FactuurBedragNetto: number | null;
  FactuurDatum: Date;
  ProjectCode: string | null;
  ProjectSoortOmschrijving: string;
}

export interface ViewInterneKosten {
  BasisBegrotingOmschrijving: string | null;
  InterneKostBasisBegrotingID: string;
  InterneKostJaar: number | null;
  InterneKostTarief: number | null;
  InternKostGUID: string;
}

export interface ViewMAProjectInfo {
  ContactFullName: string;
  ContactMail: string | null;
  ContactTelefoon: string | null;
  ProjectCode: string;
  ProjectGUID: string;
  VestigingHuisnummer: string | null;
  VestigingLand: string | null;
  VestigingNaam: string;
  VestigingPlaats: string | null;
  VestigingPostcode: string | null;
  VestigingStraat: string | null;
  VestigingTelefoon: string | null;
}

export interface ViewMedewerkers {
  ContactFullName: string;
  ContactGUID: string;
}

export interface ViewMedewerkersAll {
  ContactFullName: string;
  ContactGUID: string;
  ContactMedewerker: boolean | null;
  ContactMedewerkerActief: boolean | null;
  ProjectLeiderID: string | null;
}

export interface ViewProjectAfpuntenKosten {
  AfpuntenKostenAantal: number | null;
  AfpuntenKostenBegrotingID: string;
  AfpuntenKostenProjectID: string;
}

export interface ViewProjectAfpuntenKostenAll {
  AfpuntenKostenAantal: number | null;
  AfpuntenKostenBegrotingID: string;
  AfpuntenKostenProjectID: string;
}

export interface ViewProjectBegroting {
  BegrotingAantal: number | null;
  BegrotingBasisID: string | null;
  BegrotingGefactureerd: number | null;
  BegrotingGUID: string;
  BegrotingInfo: string | null;
  BegrotingOmschrijving: string;
  BegrotingProjectID: string | null;
  BegrotingTarief: number | null;
  BegrotingType: string;
  Prestatie: number | null;
}

export interface ViewProjectBegrotingAll {
  BegrotingAantal: number | null;
  BegrotingBasisID: string | null;
  BegrotingGefactureerd: number | null;
  BegrotingGUID: string;
  BegrotingInfo: string | null;
  BegrotingOmschrijving: string;
  BegrotingProjectID: string | null;
  BegrotingTarief: number | null;
  BegrotingType: string;
  Prestatie: number | null;
}

export interface ViewProjectenMonsternamePlanning {
  ProjectCode: string;
  RelatieNaam: string;
}

export interface ViewProjectFacturen {
  FactuurBedragNetto: number | null;
  FactuurProjectID: string | null;
}

export interface ViewProjectFacturenAll {
  FactuurBedragNetto: number | null;
  FactuurProjectID: string | null;
}

export interface ViewProjectGegevensOffice {
  DatumBevestiging: Date | null;
  FactuurRelatieBTW: string | null;
  FactuurRelatieHuisnummer: string | null;
  FactuurRelatieKlantnummer: string | null;
  FactuurRelatieLand: string | null;
  FactuurRelatieNaam: string | null;
  FactuurRelatiePlaats: string | null;
  FactuurRelatiePostcode: string | null;
  FactuurRelatieStraat: string | null;
  FactuurRelatieVestigingNaam: string | null;
  Omschrijving: string | null;
  Project: string;
  ProjectContact: string | null;
  ProjectContactEmail: string | null;
  ProjectContactGSM: string | null;
  ProjectContactGUID: string | null;
  ProjectContactTelefoon: string | null;
  ProjectFolder: string | null;
  ProjectLeider: string | null;
  ProjectLeiderEmail: string | null;
  ProjectLeiderFunctie: string | null;
  ProjectStatus: string | null;
  ProjectVestigingHuisnummer: string | null;
  ProjectVestigingLand: string | null;
  ProjectVestigingNaam: string | null;
  ProjectVestigingPlaats: string | null;
  ProjectVestigingPostcode: string | null;
  ProjectVestigingStraat: string | null;
  Referentie: string | null;
}

export interface ViewProjectMetFactuur {
  ProjectCode: string;
  ProjectDatumStart: Date | null;
  ProjectGUID: string;
  ProjectOmschrijving: string | null;
}

export interface ViewProjectRegistraties {
  ContactFullName: string | null;
  Registratie_EindUur: Date | null;
  Registratie_StartUur: Date | null;
  RegistratieBegrotingID: string | null;
  RegistratieOmschrijving: string | null;
  RegistratieProjectID: string | null;
}

export interface ViewProjectRegistratiesAll {
  ContactFullName: string | null;
  Registratie_EindUur: Date | null;
  Registratie_StartUur: Date | null;
  RegistratieBegrotingID: string | null;
  RegistratieOmschrijving: string | null;
  RegistratieProjectID: string | null;
}

export interface ViewQMILLeveranciers {
  RelatieGUID: string;
  RelatieNaam: string;
}

export interface ViewRelatieGegevensOffice {
  RelatieFolder: string | null;
  RelatieGUID: string;
  RelatieNaam: string;
  RelatieType: string | null;
  VestigingHuisnummer: string | null;
  VestigingLand: string | null;
  VestigingNaam: string;
  VestigingPlaats: string | null;
  VestigingPostcode: string | null;
  VestigingStraat: string | null;
}

export interface ViewRelatieMetContact {
  RelatieGUID: string;
  RelatieNaam: string;
}

export interface ViewRelatieMetFactuur {
  RelatieGUID: string;
  RelatieNaam: string;
}

export interface ViewRelatieMetProject {
  RelatieGUID: string;
  RelatieNaam: string;
}

export interface ViewSearchContacten {
  ContactAankoop: boolean | null;
  ContactFullName: string;
  ContactFunctie: string | null;
  ContactGSM: string | null;
  ContactGUID: string;
  ContactHistoriek: string | null;
  ContactMail: string | null;
  ContactMedewerker: boolean | null;
  ContactMedewerkerActief: boolean | null;
  ContactMedewerkerProfiel: number | null;
  ContactNaam: string;
  ContactRelatieID: string | null;
  ContactTelefoon: string | null;
  ContactVoornaam: string;
  RelatieNaam: string | null;
}

export interface ViewSearchFacturen {
  FactuurBedragBruto: number | null;
  FactuurBedragNetto: number | null;
  FactuurDateAsInt: number | null;
  FactuurDatum: Date;
  FactuurExport: boolean | null;
  FactuurGemaakt: boolean | null;
  FactuurGUID: string;
  FactuurMededeling: string | null;
  FactuurNotities: string | null;
  FactuurNummer: string;
  FactuurOK: boolean | null;
  FactuurProjectID: string | null;
  FactuurProjectSoortID: string | null;
  FactuurRelatieID: string | null;
  FactuurTitel: number;
  FactuurType: string;
  ProjectCode: string;
  ProjectDatumBevestiging: Date | null;
  ProjectLeider: string;
  ProjectOmschrijving: string | null;
  ProjectReferteKlant: string | null;
  ProjectSoortOmschrijving: string;
  RelatieKlantnummer: string | null;
  RelatieNaam: string;
  RelatieVAT: string | null;
  VestigingHuisnummer: string | null;
  VestigingLand: string | null;
  VestigingPlaats: string | null;
  VestigingPostcode: string | null;
  VestigingStraat: string | null;
}

export interface ViewSearchFacturenAll {
  FactuurBedragBruto: number | null;
  FactuurBedragNetto: number | null;
  FactuurDateAsInt: number | null;
  FactuurDatum: Date;
  FactuurExport: boolean | null;
  FactuurGemaakt: boolean | null;
  FactuurGUID: string;
  FactuurMededeling: string | null;
  FactuurNotities: string | null;
  FactuurNummer: string;
  FactuurOK: boolean | null;
  FactuurProjectID: string | null;
  FactuurProjectSoortID: string | null;
  FactuurRelatieID: string | null;
  FactuurTitel: number;
  FactuurType: string;
  ProjectCode: string;
  ProjectDatumBevestiging: Date | null;
  ProjectLeider: string;
  ProjectOmschrijving: string | null;
  ProjectReferteKlant: string | null;
  ProjectSoortOmschrijving: string;
  RelatieKlantnummer: string | null;
  RelatieNaam: string;
  RelatieVAT: string | null;
  VestigingHuisnummer: string | null;
  VestigingLand: string | null;
  VestigingPlaats: string | null;
  VestigingPostcode: string | null;
  VestigingStraat: string | null;
}

export interface ViewSearchProjecten {
  ProjectCode: string;
  ProjectContact: string | null;
  ProjectDatumBevestiging: Date | null;
  ProjectDatumEind: Date | null;
  ProjectDatumStart: Date | null;
  ProjectDeadline: Date | null;
  ProjectFacturatiePrijs: number | null;
  ProjectFolder: string | null;
  ProjectGUID: string;
  ProjectLeider: string | null;
  ProjectLeiderID: string | null;
  ProjectMedewerker: string | null;
  ProjectOmschrijving: string | null;
  ProjectReferteKlant: string | null;
  ProjectRelatieID: string | null;
  ProjectSoortID: string | null;
  ProjectSoortOmschrijving: string | null;
  ProjectStatus: string | null;
  ProjectVestigingID: string | null;
  RelatieNaam: string | null;
  VestigingNaam: string | null;
}

export interface ViewSearchProjectenAll {
  ProjectCode: string;
  ProjectContact: string | null;
  ProjectDatumBevestiging: Date | null;
  ProjectDatumEind: Date | null;
  ProjectDatumStart: Date | null;
  ProjectDeadline: Date | null;
  ProjectFacturatiePrijs: number | null;
  ProjectFolder: string | null;
  ProjectGUID: string;
  ProjectLeider: string | null;
  ProjectLeiderID: string | null;
  ProjectMedewerker: string | null;
  ProjectOmschrijving: string | null;
  ProjectReferteKlant: string | null;
  ProjectRelatieID: string | null;
  ProjectSoortID: string | null;
  ProjectSoortOmschrijving: string | null;
  ProjectStatus: string | null;
  ProjectVestigingID: string | null;
  RelatieKlantnummer: string | null;
  RelatieNaam: string | null;
  RelatieTelefoon: string | null;
  RelatieVAT: string | null;
  VestigingHuisnummer: string | null;
  VestigingLand: string | null;
  VestigingNaam: string | null;
  VestigingPlaats: string | null;
  VestigingPostcode: string | null;
  VestigingStraat: string | null;
}

export interface ViewSearchProjectenOnStart {
  ProjectCode: string;
  ProjectDatumEind: Date | null;
  ProjectDatumStart: Date | null;
  ProjectDeadline: Date | null;
  ProjectFacturatiePrijs: number | null;
  ProjectFolder: string | null;
  ProjectGUID: string;
  ProjectLeider: string | null;
  ProjectLeiderID: string | null;
  ProjectMedewerker: string | null;
  ProjectOmschrijving: string | null;
  ProjectReferteKlant: string | null;
  ProjectSoortOmschrijving: string | null;
  ProjectStatus: string | null;
  RelatieAanbrenger: string | null;
  RelatieKlantnummer: string | null;
  RelatieNaam: string | null;
  RelatieTelefoon: string | null;
  RelatieVAT: string | null;
  VestigingHuisnummer: string | null;
  VestigingLand: string | null;
  VestigingNaam: string | null;
  VestigingPlaats: string | null;
  VestigingPostcode: string | null;
  VestigingStraat: string | null;
}

export interface ViewSearchRegistraties {
  BegrotingOmschrijving: string | null;
  DateAsIntEind: number | null;
  DateAsIntStart: number | null;
  InterneTaakKlasse: string | null;
  InterneTaakOmschrijving: string | null;
  ProjectCode: string | null;
  Registratie_EindUur: Date | null;
  Registratie_StartUur: Date | null;
  RegistratieBegrotingID: string | null;
  RegistratieGUID: string;
  RegistratieInterneTaakID: string | null;
  RegistratieOmschrijving: string | null;
  RegistratieProjectID: string | null;
  RegistratieTaakVoorProject: boolean;
  RegistratieWerknemerID: string;
}

export interface ViewSearchRegistratiesShort {
  BegrotingOmschrijving: string | null;
  DateAsIntEind: number | null;
  DateAsIntStart: number | null;
  InterneTaakKlasse: string | null;
  InterneTaakOmschrijving: string | null;
  ProjectCode: string | null;
  Registratie_EindUur: Date | null;
  Registratie_StartUur: Date | null;
  RegistratieBegrotingID: string | null;
  RegistratieGUID: string;
  RegistratieInterneTaakID: string | null;
  RegistratieOmschrijving: string | null;
  RegistratieProjectID: string | null;
  RegistratieTaakVoorProject: boolean;
  RegistratieWerknemerID: string;
}

export interface ViewSearchRelaties {
  RelatieGUID: string;
  RelatieNaam: string;
}

export interface ViewSearchVestigingen {
  VestigingGUID: string;
  VestigingNaam: string;
}

export interface ViewStandaardBegroting {
  BasisBegrotingGUID: string;
  BasisBegrotingOmschrijving: string | null;
  BasisBegrotingType: string | null;
  StandaardBegrotingAantal: number | null;
  StandaardBegrotingGUID: string;
  StandaardBegrotingInfo: string | null;
  StandaardBegrotingPakketID: string | null;
  StandaardBegrotingTarief: number | null;
}

export interface ViewVerlof {
  IntAfwezigJaar: number | null;
  IntAfwezigMedewerkerID: string | null;
  InterneTaakActief: boolean | null;
  InterneTaakGUID: string;
  InterneTaakKlasse: string | null;
  InterneTaakOmschrijving: string | null;
  InterneTaakVerlof: boolean | null;
  InterneTaakVerlofMetLimiet: boolean | null;
  InterneTaakVerlofType: number | null;
  InterneTaakVoorbeelden: string | null;
}

export interface ViewVestigingen {
  VestigingActief: boolean | null;
  VestigingGUID: string;
  VestigingHistoriek: string | null;
  VestigingHuisnummer: string | null;
  VestigingLand: string | null;
  VestigingMZ: boolean | null;
  VestigingNaam: string | null;
  VestigingPlaats: string;
  VestigingPostcode: string;
  VestigingRelatieID: string | null;
  VestigingStraat: string | null;
  VestigingTelefoon: string | null;
}

export interface ViewVestigingMetProject {
  VestigingGUID: string;
  VestigingNaam: string;
}

export interface DB {
  database_firewall_rules: DatabaseFirewallRules;
  sysdiagrams: Sysdiagrams;
  tbl_AfpuntenKosten: TblAfpuntenKosten;
  tbl_Analyses: TblAnalyses;
  tbl_BasisBegroting: TblBasisBegroting;
  tbl_Begroting: TblBegroting;
  tbl_BegrotingPakket: TblBegrotingPakket;
  tbl_Contacten: TblContacten;
  tbl_Facturen: TblFacturen;
  tbl_FactuurDetails: TblFactuurDetails;
  tbl_IntAfwezig: TblIntAfwezig;
  tbl_InterneKosten: TblInterneKosten;
  tbl_InterneTaken: TblInterneTaken;
  tbl_Locaties: TblLocaties;
  tbl_Metingen: TblMetingen;
  tbl_Monstername: TblMonstername;
  tbl_Monsternamepunten: TblMonsternamepunten;
  tbl_Monsters: TblMonsters;
  tbl_Parameters: TblParameters;
  tbl_Projecten: TblProjecten;
  tbl_ProjectMemo: TblProjectMemo;
  tbl_ProjectSoorten: TblProjectSoorten;
  tbl_ProjectStatus: TblProjectStatus;
  tbl_Registraties: TblRegistraties;
  tbl_Relaties: TblRelaties;
  tbl_Sectoren: TblSectoren;
  tbl_SensorischeAnalyse: TblSensorischeAnalyse;
  tbl_StandaardBegroting: TblStandaardBegroting;
  tbl_UurTarief: TblUurTarief;
  tbl_Verval: TblVerval;
  tbl_Vestigingen: TblVestigingen;
  TriggerDebugLog: TriggerDebugLog;
  View_Aanbrenger: ViewAanbrenger;
  View_AankoopGegevens_Office: ViewAankoopGegevensOffice;
  View_ActieveProjecten: ViewActieveProjecten;
  View_Afwezig: ViewAfwezig;
  View_AppFoto: ViewAppFoto;
  View_AuteurGegevens_Office: ViewAuteurGegevensOffice;
  View_Begroting: ViewBegroting;
  View_BegrotingDetails: ViewBegrotingDetails;
  View_ContactenMetRelatie: ViewContactenMetRelatie;
  View_ContactGegevens_Office: ViewContactGegevensOffice;
  View_ContactMetProject: ViewContactMetProject;
  View_Financieel_Prestaties: ViewFinancieelPrestaties;
  View_Financieel_Product_per_Merk: ViewFinancieelProductPerMerk;
  View_InterneKosten: ViewInterneKosten;
  View_MA_ProjectInfo: ViewMAProjectInfo;
  View_Medewerkers: ViewMedewerkers;
  View_Medewerkers_All: ViewMedewerkersAll;
  View_Project_AfpuntenKosten: ViewProjectAfpuntenKosten;
  View_Project_AfpuntenKosten_All: ViewProjectAfpuntenKostenAll;
  View_Project_Begroting: ViewProjectBegroting;
  View_Project_Begroting_All: ViewProjectBegrotingAll;
  View_Project_Facturen: ViewProjectFacturen;
  View_Project_Facturen_All: ViewProjectFacturenAll;
  View_Project_Registraties: ViewProjectRegistraties;
  View_Project_Registraties_All: ViewProjectRegistratiesAll;
  View_Projecten_MonsternamePlanning: ViewProjectenMonsternamePlanning;
  View_ProjectGegevens_Office: ViewProjectGegevensOffice;
  View_ProjectMetFactuur: ViewProjectMetFactuur;
  'View_Q-MIL_Leveranciers': ViewQMILLeveranciers;
  View_RelatieGegevens_Office: ViewRelatieGegevensOffice;
  View_RelatieMetContact: ViewRelatieMetContact;
  View_RelatieMetFactuur: ViewRelatieMetFactuur;
  View_RelatieMetProject: ViewRelatieMetProject;
  View_SearchContacten: ViewSearchContacten;
  View_SearchFacturen: ViewSearchFacturen;
  View_SearchFacturenAll: ViewSearchFacturenAll;
  View_SearchProjecten: ViewSearchProjecten;
  View_SearchProjectenAll: ViewSearchProjectenAll;
  View_SearchProjectenOnStart: ViewSearchProjectenOnStart;
  View_SearchRegistraties: ViewSearchRegistraties;
  View_SearchRegistratiesShort: ViewSearchRegistratiesShort;
  View_SearchRelaties: ViewSearchRelaties;
  View_SearchVestigingen: ViewSearchVestigingen;
  View_StandaardBegroting: ViewStandaardBegroting;
  View_Verlof: ViewVerlof;
  View_Vestigingen: ViewVestigingen;
  View_VestigingMetProject: ViewVestigingMetProject;
}
